language: php
php:
    - 7.0
    - 7.1

matrix:
    include:
        - php: 7.0
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

branches:
    only:
        - master

before_script:
    - composer update --prefer-source --dev $COMPOSER_FLAGS

script:
    - bin/phpspec run -fpretty
    - bin/php-cs-fixer --diff --dry-run -v fix
